### ISSUE TITLE
Long version numbers are cut off

### ISSUE THREAD

**Issue by edwardloveall** [stephendolan/lucky_diff#26] opened 2020-07-21 01:26 UTC
Thanks for making Lucky Diff! I noticed that long version numbers are cut off. I'm using Firefox Developer Edition 79.0b9 with no zooming.

<img width="138" alt="Screen Shot 7" src="https://user-images.githubusercontent.com/49549/88002099-b0b64e00-cacf-11ea-969e-b476507e4370.png">

**Comment by stephendolan** [comment] 2020-07-28 01:41
@edwardloveall Unfortunately, I wasn't able to reproduce even with the same version of Firefox 😢 

That said, I took advantage of this issue to refactor that form to use Flexbox instead of static widths and padding/margin. Would you mind loading it up again and seeing if the issue is resolved for you?

For future reference, here's the commit restyling that top form:
https://github.com/stephendolan/lucky_diff/commit/120e63ab91be5a2bf028c1bf03569f78e81dbe64

**Comment by stephendolan** [comment] 2020-07-31 18:24
I'm going to close this for now, but can re-open if it's still an issue!

**Closed by stephendolan** 2020-07-31 18:24 UTC
Labels: bug

**Comment by edwardloveall** [comment] 2020-07-31 18:38
It is no longer an issue since your redesign. Thanks for fixing 😄
